configuration:
  mocks:
    -
      id: 1
      name: test1
      author: tengfei
      request:
        uri: /api/test/.*
        method: GET|POST|PUT|DELETE
        parameters:
          -
            name: name
            value: test.*
          -
            name: age
            value: 18
        headers:
          -
            key: Content-Type
            value: application/json
      response:
        delay: 1000
        real: false
        statusCode: 200
        format: application/json;charset=UTF-8
        headers:
          -
            key: Authorization
            value: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3eFdwcmRIbkRWdjR3WHIyb01kdXZnTnpNU05QT1dPMCIsIm5hbWUiOiI3eFdwcmRIbkRWdjR3WHIyb01kdXZnTnpNU05QT1dPMCIsInNjb3BlIjpbIioiXSwiaWF0IjoxNTQ0NDEwNjA4LCJleHAiOjE1NDQ1MzA2MDh9.ubKJJpDUafruocCXPkeO5_0KX8JxNb90BBsuj7gZ7Og
        body: {滕飞test}
    -
      id: 2
      name: test2
      author: tengfei
      request:
        uri: /api/test/.*
        method: GET|POST|PUT|DELETE
        parameters:
          -
            name: name
            value: test.*
          -
            name: age
            value: 18
        headers:
          -
            key: Content-Type
            value: application/json
      response:
        delay: 1000
        real: false
        statusCode: 200
        format: application/json;charset=UTF-8
        headers:
          -
            key: Authorization
            value: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3eFdwcmRIbkRWdjR3WHIyb01kdXZnTnpNU05QT1dPMCIsIm5hbWUiOiI3eFdwcmRIbkRWdjR3WHIyb01kdXZnTnpNU05QT1dPMCIsInNjb3BlIjpbIioiXSwiaWF0IjoxNTQ0NDEwNjA4LCJleHAiOjE1NDQ1MzA2MDh9.ubKJJpDUafruocCXPkeO5_0KX8JxNb90BBsuj7gZ7Og
        body: { 滕飞test }